# Stage 1: Build requirements
FROM python:3.11-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Stage 2: Production image
FROM python:3.11-slim
WORKDIR /app
# Copy installed dependencies from builder
COPY --from=builder /root/.local /root/.local
COPY ./app /app/app
COPY ./alembic /app/alembic
COPY ./scripts /app/scripts
COPY alembic.ini /app/alembic.ini
COPY ./scripts/docker-entrypoint-api.sh /docker-entrypoint.sh

# Ensure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/app
WORKDIR /app

RUN chmod +x /docker-entrypoint.sh

EXPOSE 8000
ENTRYPOINT ["/docker-entrypoint.sh"]
